apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot
spec:
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - name: spring-boot
          image: vitalikolek/spring-boot-ci-cd-aws
          resources:
            limits:
              memory: "2048Mi"
              cpu: "2000m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot
spec:
  type: LoadBalancer
  selector:
    app: spring-boot
  ports:
    - port: 8080
      targetPort: 8080
